#!/bin/bash

echo "Initializing Supabase database..."
echo ""
echo "Please run the following SQL in your Supabase SQL Editor:"
echo "https://rfeklguhprnaindgoygt.supabase.co/project/rfeklguhprnaindgoygt/sql"
echo ""
echo "Copy and paste the entire contents of /database/schema.sql"
echo ""
echo "This will:"
echo "  - Enable pgvector extension"
echo "  - Create all required tables"
echo "  - Set up vector search indexes"
echo "  - Insert default account"
echo ""
echo "After running the schema, create a storage bucket:"
echo "  1. Go to Storage in Supabase"
echo "  2. Create bucket named: bot-uploads"
echo "  3. Set to Private"
echo ""
